In [1]:
import h5py
import numpy as np

In [2]:
f1 = h5py.File('postera_protease2_pos_neg_train.hdf5', 'r')
f2 = h5py.File('postera_protease2_pos_neg_test.hdf5', 'r')
f3 = h5py.File('postera_protease2_pos_neg_val.hdf5', 'r')
ligand_names = list(f1.keys())

In [3]:
print(len(ligand_names))

19533


In [4]:
print(ligand_names[:31])

['104679481_protease2_1', '104679481_protease2_10', '104679481_protease2_2', '104679481_protease2_3', '104679481_protease2_4', '104679481_protease2_5', '104679481_protease2_6', '104679481_protease2_7', '104679481_protease2_8', '104679481_protease2_9', '104680060_protease2_1', '104680060_protease2_10', '104680060_protease2_2', '104680060_protease2_3', '104680060_protease2_4', '104680060_protease2_5', '104680060_protease2_6', '104680060_protease2_7', '104680060_protease2_8', '104680060_protease2_9', '1161709_protease2_1', '1161709_protease2_10', '1161709_protease2_2', '1161709_protease2_3', '1161709_protease2_4', '1161709_protease2_5', '1161709_protease2_6', '1161709_protease2_7', '1161709_protease2_8', '1161709_protease2_9', '11748279_protease2_1']


In [6]:
for name in ligand_names:
    ligand = f1[name]['ligand'] 
    label = f1[name].attrs['label'] 

    atom_coordinates = ligand[:, :3]
    atom_coordinates.shape

    atom_features = ligand[:, 3:]
    atom_features.shape

    print(f'{name}: bind={label}({type(label)}) coordinates={atom_coordinates.shape} features={atom_features.shape}')

    break

104679481_protease2_1: bind=0(<class 'numpy.int64'>) coordinates=(100, 3) features=(100, 19)


In [13]:
atoms = []
labels = {'pos': 0, 'neg': 0}
mean_position = []
for name in f1.keys():
    if name[-1] != '1':
        continue
    ligand = f1[name]['ligand']
    
    label = f1[name].attrs['label']
    if label > 0:
        labels['pos'] += 1
    else:
        labels['neg'] += 1

    atom_coordinates = ligand[:, :3]
    mean_position.append(atom_coordinates.mean(axis=0))
    
    atom_features = ligand[:, 3:]
    atoms.append(atom_features)

print(labels)
    
mean_position = np.row_stack(mean_position)
assert mean_position.shape[-1] == 3, mean_position.shape
print(f'mean position of atoms: {mean_position.mean(axis=0)}')

atoms = np.vstack(atoms)
print(f'total atoms in dataset: {atoms.shape}')
unique_atoms, counts = np.unique(atoms, return_counts=True, axis=0)

asc = np.argsort(counts)
print(f'number of distinct atoms: {counts.shape}')
print(f'greatest_freq: {counts.max()}, next_greatest_freq: {counts[asc[-2]]}, mean: {counts.mean()}, least: {counts.min()}')
print(np.hstack([counts[asc[-3:]].reshape([-1, 1]), unique_atoms[asc[-3:]]]))

for i, feature in enumerate(atoms.T):
    print(feature.shape)
    unique_values, counts = np.unique(feature, return_counts=True)
    print(f'feature_{i} has {unique_values.size} unique values {unique_values} frequency {counts}')

{'pos': 10470, 'neg': 9063}
mean position of atoms: [ 2.6895690e-09 -1.0401038e-10  1.3006661e-09]
total atoms in dataset: (1953300, 19)
number of distinct atoms: (4552,)
greatest_freq: 1409342, next_greatest_freq: 12730, mean: 429.10808435852374, least: 1
[[9.00000000e+03 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 2.00000000e+00 2.00000000e+00
  0.00000000e+00 9.99999978e-03 1.00000000e+00 1.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]
 [1.27300000e+04 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 2.00000000e+00 2.00000000e+00
  0.00000000e+00 1.00000005e-03 1.00000000e+00 1.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]
 [1.40934200e+06 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+

feature_14 has 2 unique values [0. 1.] frequency [1688349  264951]
(1953300,)
feature_15 has 2 unique values [0. 1.] frequency [1936710   16590]
(1953300,)
feature_16 has 2 unique values [0. 1.] frequency [1840361  112939]
(1953300,)
feature_17 has 2 unique values [0. 1.] frequency [1925607   27693]
(1953300,)
feature_18 has 2 unique values [0. 1.] frequency [1586680  366620]


In [9]:
atoms = []
labels = {'pos': 0, 'neg': 0}
mean_position = []
for name in f2.keys():
    if name[-1] != '1':
        continue
    ligand = f2[name]['ligand']
    
    label = f2[name].attrs['label']
    if label > 0:
        labels['pos'] += 1
    else:
        labels['neg'] += 1

    atom_coordinates = ligand[:, :3]
    mean_position.append(atom_coordinates.mean(axis=0))
    
    atom_features = ligand[:, 3:]
    atoms.append(atom_features)

print(labels)
    
mean_position = np.row_stack(mean_position)
assert mean_position.shape[-1] == 3, mean_position.shape
print(f'mean position of atoms: {mean_position.mean(axis=0)}')

atoms = np.vstack(atoms)
print(f'total atoms in dataset: {atoms.shape}')
unique_atoms, counts = np.unique(atoms, return_counts=True, axis=0)

asc = np.argsort(counts)
print(f'number of distinct atoms: {counts.shape}')
print(f'greatest_freq: {counts.max()}, next_greatest_freq: {counts[asc[-2]]}, mean: {counts.mean()}, least: {counts.min()}')
print(np.hstack([counts[asc[-3:]].reshape([-1, 1]), unique_atoms[asc[-3:]]]))

for i, feature in enumerate(atoms.T):
    print(feature.shape)
    unique_values, counts = np.unique(feature, return_counts=True)
    print(f'feature_{i} has {unique_values.size} unique values {unique_values} frequency {counts}')

{'pos': 68, 'neg': 60}
mean position of atoms: [ 1.3820829e-08  8.2119360e-09 -4.2170281e-08]
total atoms in dataset: (12800, 19)
number of distinct atoms: (1414,)
greatest_freq: 9320, next_greatest_freq: 87, mean: 9.052333804809052, least: 1
[[4.60000000e+01 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 2.00000000e+00 2.00000000e+00
  0.00000000e+00 1.00000005e-03 1.00000000e+00 1.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]
 [8.70000000e+01 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 2.00000000e+00 2.00000000e+00
  0.00000000e+00 0.00000000e+00 1.00000000e+00 1.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]
 [9.32000000e+03 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.0000000

In [10]:
atoms = []
labels = {'pos': 0, 'neg': 0}
mean_position = []
for name in f3.keys():
    if name[-1] != '1':
        continue
    ligand = f3[name]['ligand']
    
    label = f3[name].attrs['label']
    if label > 0:
        labels['pos'] += 1
    else:
        labels['neg'] += 1

    atom_coordinates = ligand[:, :3]
    mean_position.append(atom_coordinates.mean(axis=0))
    
    atom_features = ligand[:, 3:]
    atoms.append(atom_features)

print(labels)
    
mean_position = np.row_stack(mean_position)
assert mean_position.shape[-1] == 3, mean_position.shape
print(f'mean position of atoms: {mean_position.mean(axis=0)}')

atoms = np.vstack(atoms)
print(f'total atoms in dataset: {atoms.shape}')
unique_atoms, counts = np.unique(atoms, return_counts=True, axis=0)

asc = np.argsort(counts)
print(f'number of distinct atoms: {counts.shape}')
print(f'greatest_freq: {counts.max()}, next_greatest_freq: {counts[asc[-2]]}, mean: {counts.mean()}, least: {counts.min()}')
print(np.hstack([counts[asc[-3:]].reshape([-1, 1]), unique_atoms[asc[-3:]]]))

for i, feature in enumerate(atoms.T):
    print(feature.shape)
    unique_values, counts = np.unique(feature, return_counts=True)
    print(f'feature_{i} has {unique_values.size} unique values {unique_values} frequency {counts}')

{'pos': 62, 'neg': 51}
mean position of atoms: [ 1.5127979e-08 -1.1185102e-08  5.2325517e-09]
total atoms in dataset: (11300, 19)
number of distinct atoms: (1168,)
greatest_freq: 8223, next_greatest_freq: 67, mean: 9.674657534246576, least: 1
[[5.60000000e+01 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 2.00000000e+00 2.00000000e+00
  0.00000000e+00 1.00000005e-03 1.00000000e+00 1.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]
 [6.70000000e+01 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 2.00000000e+00 2.00000000e+00
  0.00000000e+00 0.00000000e+00 1.00000000e+00 1.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]
 [8.22300000e+03 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.0000000

In [6]:
name = ligand_names[0]
ligand = f[name]['ligand']
label = f[name].attrs['label']

atom_coordinates = ligand[:, :3]
atom_coordinates.shape

atom_features = ligand[:, 3:]
atom_features.shape

for i, features in enumerate(atom_features):
    if features.sum() == 0:
        print(f'{i}:\t coords={atom_coordinates[i]} features={features}')

37:	 coords=[0. 0. 0.] features=[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
38:	 coords=[0. 0. 0.] features=[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
39:	 coords=[0. 0. 0.] features=[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
40:	 coords=[0. 0. 0.] features=[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
41:	 coords=[0. 0. 0.] features=[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
42:	 coords=[0. 0. 0.] features=[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
43:	 coords=[0. 0. 0.] features=[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
44:	 coords=[0. 0. 0.] features=[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
45:	 coords=[0. 0. 0.] features=[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
46:	 coords=[0. 0. 0.] features=[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
47:	 coords=[0. 0. 0.] features=[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

After analyzing the data, there are only 9 different atoms (one-hot encoding features 0-8) in this dataset. However there may not be enough data to make good embeddings for each atom e.g., (atoms 4, and 8 rarely appear and atoms 0, 6 never do). 

It may be necessary to make separate embeddings based on the other 19 descriptors (features 9-18). However, feature 12 has an infinite range of values, so it cannot be used to train embeddings.

After having embeddings for both the atom type and their descriptors, they can be concatenated. Additionally, feature 12 can be concatenated with the embeddings too.

# Example Dataloader

In [14]:
import torch
from torch import tensor
from torch.utils.data import Dataset, DataLoader

class LigandsDataset(Dataset):
    def __init__(self, hdf5_path):
        super(AtomsDataset, self).__init__()
        self.File = h5py.File(hdf5_path, 'r')
        self.ligand_names = list(self.File.keys())
        
    def __len__(self):
        return len(self.ligand_names)
    
    def __getitem__(self, x):
        name = self.ligand_names[x]
        ligand = self.File[name]['ligand']
        label = tensor(self.File[name].attrs['label'])
        
        coordinates = tensor(ligand[:, :3])
        features = tensor(ligand[:, 3:])
        
        return coordinates, features, label 

In [15]:
dataset = LigandsDataset('postera_protease2_pos_neg_train.hdf5')

In [18]:
coords, features, label = dataset[0]

print(coords.shape, features.shape, label.shape)

torch.Size([100, 3]) torch.Size([100, 19]) torch.Size([])


# Embedding Dicts and IDs

Creates 2 embedding dictionary matrices (saves to atoms.pt and descriptors.pt) for each unique atom and set of descriptors

Then creates a new HDF5 file with all ligand graphs from the postera dataset with the embedding ID for each atoms and their descriptors (as their own datasets).

###  Dictionaries

In [1]:
import h5py
import numpy as np

In [11]:
f1 = h5py.File('postera_protease2_pos_neg_train.hdf5', 'r')
f2 = h5py.File('postera_protease2_pos_neg_test.hdf5', 'r')
f3 = h5py.File('postera_protease2_pos_neg_val.hdf5', 'r')

Just in case, check the number of unique atoms in the datasets.

In [19]:
atoms = []
atom_descriptors = []
for name in f1.keys():
    if name[-1] != '1':
        continue
    ligand = f1[name]['ligand'][:, 3:]
    atom_onehot = ligand[:, :9]
    atoms.append(atom_onehot)
    descriptors = (ligand[:, 9:12], ligand[:, 13:]) # skip feature 12 because it has an infinite domain
    atom_descriptors.append(np.hstack(descriptors))
    
for name in f2.keys():
    if name[-1] != '1':
        continue
    ligand = f2[name]['ligand'][:, 3:]
    atom_onehot = ligand[:, :9]
    atoms.append(atom_onehot)
    descriptors = (ligand[:, 9:12], ligand[:, 13:])
    atom_descriptors.append(np.hstack(descriptors))
    
for name in f3.keys():
    if name[-1] != '1':
        continue
    ligand = f3[name]['ligand'][:, 3:]
    atom_onehot = ligand[:, :9]
    atoms.append(atom_onehot)
    descriptors = (ligand[:, 9:12], ligand[:, 13:])
    atom_descriptors.append(np.hstack(descriptors))

atoms = np.vstack(atoms)
print(f'total atoms in dataset: {atoms.shape}')
unique_atoms, counts = np.unique(atoms, return_counts=True, axis=0)

asc = np.argsort(counts)
print(f'number of distinct atoms: {counts.shape}')
print(f'greatest_freq: {counts.max()}, next_greatest_freq: {counts[asc[-2]]}, mean: {counts.mean()}, least: {counts.min()}')

atoms_sorted = unique_atoms[asc[:-1]]
atoms_sorted = np.flipud(atoms_sorted)
print(atoms_sorted)

total atoms in dataset: (219600, 9)
number of distinct atoms: (8,)
greatest_freq: 158581, next_greatest_freq: 45384, mean: 27450.0, least: 1
[[0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


Also, check the number of unqiue descriptors in the dataset.

In [20]:
atom_descriptors = np.vstack(atom_descriptors)
print(f'total descriptors in dataset: {atom_descriptors.shape}')
unique_descriptors, counts = np.unique(atom_descriptors, return_counts=True, axis=0)

asc = np.argsort(counts)
print(f'number of distinct descriptors: {counts.shape}')
print(f'greatest_freq: {counts.max()}, next_greatest_freq: {counts[asc[-2]]}, mean: {counts.mean()}, least: {counts.min()}')

descriptors_sorted = unique_descriptors[asc[:-1]]
descriptors_sorted = np.flipud(descriptors_sorted)
print(descriptors_sorted)

total descriptors in dataset: (219600, 9)
number of distinct descriptors: (139,)
greatest_freq: 158581, next_greatest_freq: 15284, mean: 1579.8561151079136, least: 1
[[2. 2. 0. ... 0. 0. 1.]
 [2. 3. 0. ... 0. 0. 1.]
 [2. 3. 1. ... 0. 0. 1.]
 ...
 [2. 3. 2. ... 1. 0. 1.]
 [2. 3. 1. ... 1. 1. 0.]
 [6. 6. 0. ... 0. 0. 0.]]


In [ ]:
import torch
from torch import tensor

Save both matrices (which are embedding dictionaries) for later use.

In [ ]:
cpy = atoms_sorted.copy()
torch.save(tensor(cpy), 'atoms.pt')

cpy = descriptors_sorted.copy()
torch.save(tensor(cpy), 'descriptors.pt')

Write a helper function that finds the index in our embed dict that contains the given vector. Otherwise returns -1

In [23]:
def get_id(embed, vec):
    if np.all(vec == 0):
        return -1
    assert vec.shape[-1] == embed.shape[-1], (vec.shape, embed.shape)
    element_comp = np.equal(embed, vec)
    row_comp = np.all(element_comp, axis=1)
    indices = np.argwhere(row_comp)
    assert indices.size == 1, f'onehot {onehot}\nindices {indices}\n'
    return indices.item()

Create the HDF5 file to write in

In [ ]:
outfile = h5py.File('postera_protease2_id_graph.hdf5','w')

Translate the ligand graphs from the training, testing, and validation HDF5 files into our graphs of our embedding IDs

In [29]:
for i, name in enumerate(f1.keys()):
    if name[-1] != '1':
        continue
    grp = outfile.create_group(name)
    
    old_ligand = f1[name]['ligand']
    old_label = f1[name].attrs['label']
    new_label = grp.attrs.create('label', old_label)

    atom_coordinates = old_ligand[:, :3] # (100, 3)
    atom_onehot = old_ligand[:, 3:12] # (100, 9)
    atom_descriptors = np.hstack((old_ligand[:, 12:15], old_ligand[:, 16:]))
    
    copy_coordinates = grp.create_dataset('coordinates', (100, 3))
    copy_coordinates[()] = atom_coordinates
    
    print('.', end='') # initialized ligand group and created atom coordinates dataset
    
    ligand_atoms = grp.create_dataset('atoms', (100, 1), dtype='i8')
    
    atoms = []
    for vec in atom_onehot:
        atoms.append(get_id(atoms_sorted, vec))
        
    atoms = np.array(atoms)
    atoms = np.expand_dims(atoms, -1)
    assert atoms.shape == (100, 1), atoms.shape
    
    ligand_atoms[()] = atoms
    
    print('.', end='') # created ligand's atom dataset with atom ids
    
    ligand_descriptors = grp.create_dataset('descriptors', (100, 1), dtype='i8')
    
    descriptors = []
    for vec in atom_descriptors:
        descriptors.append(get_id(descriptors_sorted, vec))
        
    descriptors = np.array(descriptors)
    descriptors = np.expand_dims(descriptors, -1)
    assert descriptors.shape == (100, 1), descriptors.shape
    
    ligand_descriptors[()] = descriptors
    
    print('.', end='') # created ligand's descriptors dataset with descriptor ids
    
    print(i)

...0
...10
...20
...30
...40
...50
...60
...70
...80
...90
...100
...110
...120
...130
...140
...150
...160
...170
...180
...190
...200
...210
...220
...230
...240
...250
...260
...270
...280
...290
...300
...310
...320
...330
...340
...350
...360
...370
...380
...390
...400
...410
...420
...430
...440
...450
...460
...470
...480
...490
...500
...510
...520
...530
...540
...550
...560
...570
...580
...590
...600
...610
...620
...630
...640
...650
...660
...670
...680
...690
...700
...710
...720
...730
...740
...750
...760
...770
...780
...790
...800
...810
...820
...830
...840
...850
...860
...870
...880
...890
...900
...910
...920
...930
...940
...950
...960
...970
...980
...990
...1000
...1010
...1020
...1030
...1040
...1050
...1060
...1070
...1080
...1090
...1100
...1110
...1120
...1130
...1140
...1150
...1160
...1170
...1180
...1190
...1200
...1210
...1220
...1230
...1240
...1250
...1260
...1270
...1280
...1290
...1300
...1310
...1320
...1330
...1340
...1350
...1360
...1370
...1380

...10492
...10502
...10512
...10522
...10532
...10542
...10552
...10562
...10572
...10582
...10592
...10602
...10612
...10622
...10632
...10642
...10652
...10662
...10672
...10682
...10692
...10702
...10712
...10722
...10732
...10742
...10752
...10762
...10772
...10782
...10792
...10802
...10812
...10822
...10832
...10842
...10852
...10862
...10872
...10882
...10892
...10902
...10912
...10922
...10932
...10942
...10952
...10962
...10972
...10982
...10992
...11002
...11012
...11022
...11032
...11042
...11052
...11062
...11072
...11082
...11092
...11102
...11112
...11122
...11132
...11142
...11152
...11162
...11172
...11182
...11192
...11202
...11212
...11222
...11232
...11242
...11252
...11262
...11272
...11282
...11292
...11302
...11312
...11322
...11332
...11342
...11352
...11362
...11372
...11382
...11392
...11402
...11412
...11422
...11432
...11442
...11452
...11462
...11472
...11482
...11492
...11502
...11512
...11522
...11532
...11542
...11552
...11562
...11572
...11582
...11592
.

In [31]:
for i, name in enumerate(f2.keys()):
    if name[-1] != '1':
        continue
    grp = outfile.create_group(name)
    
    old_ligand = f2[name]['ligand']
    old_label = f2[name].attrs['label']
    new_label = grp.attrs.create('label', old_label)

    atom_coordinates = old_ligand[:, :3] # (100, 3)
    atom_onehot = old_ligand[:, 3:12] # (100, 9)
    atom_descriptors = np.hstack((old_ligand[:, 12:15], old_ligand[:, 16:]))
    
    copy_coordinates = grp.create_dataset('coordinates', (100, 3))
    copy_coordinates[()] = atom_coordinates
    
    print('.', end='') # initialized ligand group and created atom coordinates dataset
    
    ligand_atoms = grp.create_dataset('atoms', (100, 1), dtype='i8')
    
    atoms = []
    for vec in atom_onehot:
        atoms.append(get_id(atoms_sorted, vec))
        
    atoms = np.array(atoms)
    atoms = np.expand_dims(atoms, -1)
    assert atoms.shape == (100, 1), atoms.shape
    
    ligand_atoms[()] = atoms
    
    print('.', end='') # created ligand's atom dataset with atom ids
    
    ligand_descriptors = grp.create_dataset('descriptors', (100, 1), dtype='i8')
    
    descriptors = []
    for vec in atom_descriptors:
        descriptors.append(get_id(descriptors_sorted, vec))
        
    descriptors = np.array(descriptors)
    descriptors = np.expand_dims(descriptors, -1)
    assert descriptors.shape == (100, 1), descriptors.shape
    
    ligand_descriptors[()] = descriptors
    
    print('.', end='') # created ligand's descriptors dataset with descriptor ids
    
    print(i)

...0
...10
...20
...30
...40
...50
...60
...70
...80
...90
...100
...110
...120
...130
...140
...150
...160
...170
...180
...190
...200
...210
...220
...230
...240
...250
...260
...270
...280
...290
...300
...310
...320
...330
...340
...350
...360
...370
...380
...390
...400
...410
...420
...430
...440
...450
...460
...470
...480
...490
...500
...510
...520
...530
...540
...550
...560
...570
...580
...590
...600
...610
...620
...630
...640
...650
...660
...670
...680
...690
...700
...710
...720
...730
...740
...750
...760
...770
...780
...790
...800
...810
...820
...830
...840
...850
...860
...870
...880
...890
...900
...910
...920
...930
...940
...950
...960
...970
...980
...990
...1000
...1010
...1020
...1030
...1040
...1050
...1060
...1070
...1080
...1090
...1100
...1110
...1120
...1130
...1140
...1150
...1160
...1170
...1180
...1190
...1200
...1210
...1220
...1230
...1240
...1250
...1260
...1270


In [32]:
for i, name in enumerate(f3.keys()):
    if name[-1] != '1':
        continue
    grp = outfile.create_group(name)
    
    old_ligand = f3[name]['ligand']
    old_label = f3[name].attrs['label']
    new_label = grp.attrs.create('label', old_label)

    atom_coordinates = old_ligand[:, :3] # (100, 3)
    atom_onehot = old_ligand[:, 3:12] # (100, 9)
    atom_descriptors = np.hstack((old_ligand[:, 12:15], old_ligand[:, 16:]))
    
    copy_coordinates = grp.create_dataset('coordinates', (100, 3))
    copy_coordinates[()] = atom_coordinates
    
    print('.', end='') # initialized ligand group and created atom coordinates dataset
    
    ligand_atoms = grp.create_dataset('atoms', (100, 1), dtype='i8')
    
    atoms = []
    for vec in atom_onehot:
        atoms.append(get_id(atoms_sorted, vec))
        
    atoms = np.array(atoms)
    atoms = np.expand_dims(atoms, -1)
    assert atoms.shape == (100, 1), atoms.shape
    
    ligand_atoms[()] = atoms
    
    print('.', end='') # created ligand's atom dataset with atom ids
    
    ligand_descriptors = grp.create_dataset('descriptors', (100, 1), dtype='i8')
    
    descriptors = []
    for vec in atom_descriptors:
        descriptors.append(get_id(descriptors_sorted, vec))
        
    descriptors = np.array(descriptors)
    descriptors = np.expand_dims(descriptors, -1)
    assert descriptors.shape == (100, 1), descriptors.shape
    
    ligand_descriptors[()] = descriptors
    
    print('.', end='') # created ligand's descriptors dataset with descriptor ids
    
    print(i)

...0
...10
...20
...30
...40
...50
...60
...70
...80
...90
...100
...110
...120
...130
...140
...150
...160
...170
...180
...190
...200
...210
...220
...230
...240
...250
...260
...270
...280
...290
...300
...310
...320
...330
...340
...350
...360
...370
...380
...390
...400
...410
...420
...430
...440
...450
...460
...470
...480
...490
...500
...510
...520
...530
...540
...550
...560
...570
...580
...590
...600
...610
...620
...630
...640
...650
...660
...670
...680
...690
...700
...710
...720
...730
...740
...750
...760
...770
...780
...790
...800
...810
...820
...830
...840
...850
...860
...870
...880
...890
...900
...910
...920
...930
...940
...950
...960
...970
...980
...990
...1000
...1010
...1020
...1030
...1040
...1050
...1060
...1070
...1080
...1090
...1100
...1110
...1120


Last sanity checks

In [33]:
ligand_names = list(outfile.keys())
print(ligand_names)

['104679481_protease2_1', '104680060_protease2_1', '1161709_protease2_1', '11748279_protease2_1', '11798390_protease2_1', '11808502_protease2_1', '12604832_protease2_1', '1321130_protease2_1', '13987632_protease2_1', '16016872_protease2_1', '16135771_protease2_1', '16292231_protease2_1', '1679888_protease2_1', '17179139_protease2_1', '171822134_protease2_1', '171835375_protease2_1', '171966708_protease2_1', '1812803_protease2_1', '18857566_protease2_1', '24322185_protease2_1', '24346622_protease2_1', '24424670_protease2_1', '24425568_protease2_1', '24437634_protease2_1', '25392386_protease2_1', '25545621_protease2_1', '26174112_protease2_1', '2943672_protease2_1', '300146207_protease2_1', '30536096_protease2_1', '3172642_protease2_1', '32494230_protease2_1', '32782830_protease2_1', '35936444_protease2_1', '4204459_protease2_1', '43679490_protease2_1', '43680058_protease2_1', '43756189_protease2_1', '43838718_protease2_1', '43872339_protease2_1', '43926720_protease2_1', '43966586_protea

In [30]:
for name in outfile.keys():
    print(name)
    coordinates = outfile[name]['coordinates'][()]
    atoms = outfile[name]['atoms'][()]
    descriptors = outfile[name]['descriptors'][()]
    label = outfile[name].attrs['label']
    print(coordinates.shape)
    print(atoms.shape, atoms)
    print(descriptors.shape, descriptors)
    print(label.shape, label)
    break

104679481_protease2_1
(100, 3)
(100, 1) [[ 0]
 [ 0]
 [ 0]
 [ 1]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 1]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 1]
 [ 0]
 [ 1]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 2]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]]
(100, 1) [[23]
 [11]
 [18]
 [ 7]
 [ 2]
 [ 1]
 [ 2]
 [ 0]
 [ 0]
 [ 0]
 [17]
 [ 4]
 [ 1]
 [ 1]
 [ 0]
 [ 1]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 2]
 [ 7]
 [18]
 [17]
 [ 6]
 [11]
 [11]
 [11]
 [ 6]
 [26]
 [10]
 [ 1]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [

In [35]:
outfile.close()
f1.close()
f2.close()
f3.close()

### Sequence Generation

Now to write a dataloader that generates sequences from our new embedding dataset, which can be used to learn graph embeddings.

In [32]:
import h5py
import numpy as np
from numpy.random import default_rng

In [63]:
graphs = h5py.File('postera_protease2_id_graph.hdf5','r')
atom_seq_dataset = open('atom_sequences.csv', 'w')
descriptor_seq_dataset = open('descriptor_sequences.csv', 'w')

In [64]:
def log_softmax(x):
    c = x.max()
    logsumexp = np.log(np.exp(x - c).sum())
    return x - c - logsumexp

# gets the neighbors of node within a given radius
# distance matrix should be a square matrix
# (optional) list of ban nodes which should not be considered
# returns the node IDs of the neighbors
# also returns the log probability vector based on their distance
def get_neighbors(node, distance_mat, radius, ban=[]):
    neighbors = np.nonzero(distance_mat[node, :] <= radius)[0]
    
    if neighbors.size and ban:
        conditions = sum([neighbors == x for x in ban])
        mask = np.nonzero(conditions == 0)
        neighbors = neighbors[mask]
        
    if neighbors.size == 0:
        return [], []
    
    distances = distance_mat[node, neighbors]
    log_probs = log_softmax(radius - distances)
    # increment neighbor ids because distance matrix excludes diagonal
    return neighbors, log_probs

In [66]:
rng = default_rng()
k = 100

num_graphs = len(graphs.keys())
# generate k sequences per graph
for i, name in enumerate(graphs.keys()):
    coords = graphs[name]['coordinates'][()]
    atoms = graphs[name]['atoms'][()]
    descriptors = graphs[name]['descriptors'][()]
    
    # find and extract non-padding rows
    assert coords.ndim == 2, coords.shape
    rows = np.all(coords != 0, axis=1)
    indices = np.nonzero(rows)
    coords = coords[indices]
    atoms = atoms[indices]
    descriptors = descriptors[indices]
    
    # find good neighborhood radius (2 times the mean of shortest distances between atoms)
    # for distance_matrix calculation see pytorch documents for pdist
    # https://pytorch.org/docs/stable/generated/torch.nn.functional.pdist.html
    # diagonal is set to infinity 
    distance_matrix = np.linalg.norm((coords[:, None] - coords), axis=-1)
    distance_matrix[distance_matrix == 0] = np.inf
    radius = distance_matrix.min(axis=1).mean() * 2
    
    # generate random sequences
    for _ in range(k):
        # initial node to begin sequence
        node = rng.choice(indices[0])

        # initialize sequences to be written
        atom_seq = [atoms[node].item()]
        descriptor_seq = [descriptors[node].item()]

        # add node to ban list
        ban = [node]

        # get neighborhood and hop to a random neighbor
        neighbors, log_probs = get_neighbors(node, distance_matrix, radius, ban)
        while len(neighbors):
            node = rng.choice(neighbors, p=np.exp(log_probs))
            atom_seq.append(atoms[node].item())
            descriptor_seq.append(descriptors[node].item())
            ban.append(node)
            neighbors, log_probs = get_neighbors(node, distance_matrix, radius, ban)
        
        # save sequences to csv dataset
        # each line is a sequence
        atom_seq_dataset.write(','.join(map(str, atom_seq)) + '\n')
        descriptor_seq_dataset.write(','.join(map(str, descriptor_seq)) + '\n')
    
    print(f'{i}/{num_graphs}')

0/2196
1/2196
2/2196
3/2196
4/2196
5/2196
6/2196
7/2196
8/2196
9/2196
10/2196
11/2196
12/2196
13/2196
14/2196
15/2196
16/2196
17/2196
18/2196
19/2196
20/2196
21/2196
22/2196
23/2196
24/2196
25/2196
26/2196
27/2196
28/2196
29/2196
30/2196
31/2196
32/2196
33/2196
34/2196
35/2196
36/2196
37/2196
38/2196
39/2196
40/2196
41/2196
42/2196
43/2196
44/2196
45/2196
46/2196
47/2196
48/2196
49/2196
50/2196
51/2196
52/2196
53/2196
54/2196
55/2196
56/2196
57/2196
58/2196
59/2196
60/2196
61/2196
62/2196
63/2196
64/2196
65/2196
66/2196
67/2196
68/2196
69/2196
70/2196
71/2196
72/2196
73/2196
74/2196
75/2196
76/2196
77/2196
78/2196
79/2196
80/2196
81/2196
82/2196
83/2196
84/2196
85/2196
86/2196
87/2196
88/2196
89/2196
90/2196
91/2196
92/2196
93/2196
94/2196
95/2196
96/2196
97/2196
98/2196
99/2196
100/2196
101/2196
102/2196
103/2196
104/2196
105/2196
106/2196
107/2196
108/2196
109/2196
110/2196
111/2196
112/2196
113/2196
114/2196
115/2196
116/2196
117/2196
118/2196
119/2196
120/2196
121/2196
122/2196
123

925/2196
926/2196
927/2196
928/2196
929/2196
930/2196
931/2196
932/2196
933/2196
934/2196
935/2196
936/2196
937/2196
938/2196
939/2196
940/2196
941/2196
942/2196
943/2196
944/2196
945/2196
946/2196
947/2196
948/2196
949/2196
950/2196
951/2196
952/2196
953/2196
954/2196
955/2196
956/2196
957/2196
958/2196
959/2196
960/2196
961/2196
962/2196
963/2196
964/2196
965/2196
966/2196
967/2196
968/2196
969/2196
970/2196
971/2196
972/2196
973/2196
974/2196
975/2196
976/2196
977/2196
978/2196
979/2196
980/2196
981/2196
982/2196
983/2196
984/2196
985/2196
986/2196
987/2196
988/2196
989/2196
990/2196
991/2196
992/2196
993/2196
994/2196
995/2196
996/2196
997/2196
998/2196
999/2196
1000/2196
1001/2196
1002/2196
1003/2196
1004/2196
1005/2196
1006/2196
1007/2196
1008/2196
1009/2196
1010/2196
1011/2196
1012/2196
1013/2196
1014/2196
1015/2196
1016/2196
1017/2196
1018/2196
1019/2196
1020/2196
1021/2196
1022/2196
1023/2196
1024/2196
1025/2196
1026/2196
1027/2196
1028/2196
1029/2196
1030/2196
1031/2196
1032/

1754/2196
1755/2196
1756/2196
1757/2196
1758/2196
1759/2196
1760/2196
1761/2196
1762/2196
1763/2196
1764/2196
1765/2196
1766/2196
1767/2196
1768/2196
1769/2196
1770/2196
1771/2196
1772/2196
1773/2196
1774/2196
1775/2196
1776/2196
1777/2196
1778/2196
1779/2196
1780/2196
1781/2196
1782/2196
1783/2196
1784/2196
1785/2196
1786/2196
1787/2196
1788/2196
1789/2196
1790/2196
1791/2196
1792/2196
1793/2196
1794/2196
1795/2196
1796/2196
1797/2196
1798/2196
1799/2196
1800/2196
1801/2196
1802/2196
1803/2196
1804/2196
1805/2196
1806/2196
1807/2196
1808/2196
1809/2196
1810/2196
1811/2196
1812/2196
1813/2196
1814/2196
1815/2196
1816/2196
1817/2196
1818/2196
1819/2196
1820/2196
1821/2196
1822/2196
1823/2196
1824/2196
1825/2196
1826/2196
1827/2196
1828/2196
1829/2196
1830/2196
1831/2196
1832/2196
1833/2196
1834/2196
1835/2196
1836/2196
1837/2196
1838/2196
1839/2196
1840/2196
1841/2196
1842/2196
1843/2196
1844/2196
1845/2196
1846/2196
1847/2196
1848/2196
1849/2196
1850/2196
1851/2196
1852/2196
1853/2196


In [67]:
graphs.close()
atom_seq_dataset.close()
descriptor_seq_dataset.close()